<?php $this->flashSession->output() ?>
<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12">
        <div class="card-box">
            <div class="page-header">
                <h1>Sistem Informasi Penggajian</h1>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card-box">
            <h3>Rule Tanggungan</h3>
            <h4>1. K/0 Tanggunan 0</h4>
            <h4>1. K/1 Tanggunan 1</h4>
            <h4>1. K/2 Tanggunan 2</h4>
            <h4>1. K/3 Tanggunan 3</h4>
            <h4>TK/0 Tanggunan 0</h4>
            <h4>TK/1 Tanggunan 1</h4>
            <h4>TK/2 Tanggunan 2</h4>
            <h4>TK/4 Tanggunan 3</h4>
            <code>Jika Ada 4 Tanggungan Maka Tetep di anggap 3</code>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card-box">
            <h3>PPH</h3>
            <h4>1. Awal Tahun</h4>
            <h4>2. Tengah Tahun</h4>
            <h4>3. Akhir Tahun</h4>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card-box">
            <h3>Rule Lembur</h3>
            <h4>Lembur = <span class="text-danger">Gaji Pokok</span> : 173 = <span
                        class="text-success">Lembur / Jam</span></h4>
            <h4>Lembur Hidup : 1 <span class="text-primary">X</span> 1,5 Jam = 1,5</h4>
            <h4 class="alert alert-success">Untuk perusahaan dengan 6 hari kerja, rate adalah 2x upah sejam untuk 7 jam
                pertama, 3x upah sejam untuk
                jam ke-8, dan 4x upah sejam untuk jam ke-9 dan ke-10.</h4>
            <h4 class="alert alert-warning">Untuk hari libur yang jatuh pada hari kerja terpendek (misalnya Jumat), rate
                adalah 2x upah sejam untuk 5 jam pertama, 3x upah sejam pada jam ke-6, dan 4x upah sejam pada jam ke-7
                dan ke-8.</h4>
        </div>
    </div>
</div>