<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <!-- App Favicon -->
    <link rel="shortcut icon" href="<?= $this->url->get('') ?>assets/images/favicon.ico">

    <!-- App title -->
    <title>SIP SSP</title>

    <link href="<?= $this->url->get('') ?>assets/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css"
          rel="stylesheet"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/multiselect/css/multi-select.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/select2/dist/css/select2.css" rel="stylesheet" type="text/css">
    <link href="<?= $this->url->get('') ?>assets/plugins/select2/dist/css/select2-bootstrap.css" rel="stylesheet"
          type="text/css">
    <link href="<?= $this->url->get('') ?>assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css"
          rel="stylesheet"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/switchery/switchery.min.css" rel="stylesheet"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet">
    <link href="<?= $this->url->get('') ?>assets/plugins/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css"
          rel="stylesheet">
    <link href="<?= $this->url->get('') ?>assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css"
          rel="stylesheet">
    <link href="<?= $this->url->get('') ?>assets/plugins/bootstrap-daterangepicker/daterangepicker.css"
          rel="stylesheet">

    <!-- DataTables -->
    <link href="<?= $this->url->get('') ?>assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/datatables/buttons.bootstrap.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/plugins/datatables/scroller.bootstrap.min.css" rel="stylesheet"
          type="text/css"/>

    <!-- App CSS -->
    <link href="<?= $this->url->get('') ?>assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/core.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/components.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/icons.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/pages.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/menu.css" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>assets/css/responsive.css" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="<?= $this->url->get('') ?>assets/js/modernizr.min.js"></script>

</head>

<?php if ($this->session->get('idPengguna')): ?>
<body class="fixed-left">
<!-- Begin page -->
<div id="wrapper">

    <!-- Top Bar Start -->
    <div class="topbar">

        <!-- LOGO -->
        <div class="topbar-left">
            <a href="<?= $this->url->get('') ?>" class="logo"><span>SIP<span>SSP</span></span><i
                        class="zmdi zmdi-layers"></i></a>
        </div>

        <!-- Button mobile view to collapse sidebar menu -->
        <div class="navbar navbar-default" role="navigation">
            <div class="container">

                <!-- Page title -->
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button class="button-menu-mobile open-left">
                            <i class="zmdi zmdi-menu"></i>
                        </button>
                    </li>
                </ul>


            </div><!-- end container -->
        </div><!-- end navbar -->
    </div>
    <!-- Top Bar End -->


    <!-- ========== Left Sidebar Start ========== -->
    <div class="left side-menu">
        <div class="sidebar-inner slimscrollleft">

            <!-- User -->
            <div class="user-box">
                <div class="user-img">
                    <img src="<?= $this->url->get('') ?>assets/images/users/avatar-1.jpg" alt="user-img"
                         title="Mat Helme" class="img-circle img-thumbnail img-responsive">
                    <div class="user-status offline"><i class="zmdi zmdi-dot-circle"></i></div>
                </div>
                <h5><a href="#"><?= $this->session->get('namatenagakerja') ?></a></h5>
                <ul class="list-inline">
                    <li>
                        <a href="<?= $this->url->get('index/lupa') ?>">
                            <i class="zmdi zmdi-settings"></i>
                        </a>
                    </li>

                    <li>
                        <a href="<?= $this->url->get('session/logout') ?>" class="text-custom">
                            <i class="zmdi zmdi-power"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- End User -->

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <ul>
                    <li>
                        <a href="<?= $this->url->get('index') ?>" class="waves-effect"><i
                                    class="zmdi zmdi-view-dashboard"></i> <span> Dashboard </span>
                        </a>
                    </li>
                    <?php if ($this->session->get('hak') == 'Personalia'): ?>
                        <li class="text-muted menu-title">Navigation Admin</li>

                        

                        <li>
                            <a href="<?= $this->url->get('absen') ?>" class="waves-effect"><i
                                        class="fa fa-user"></i> <span>Data Master Absen</span>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('spl') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Pembuatan SPL</span>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('index/tunjungan') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Tunjangan</span>
                            </a>
                        </li>
                        <li class="text-muted menu-title">Navigation PPH21</li>
                        <li>
                            <a href="<?= $this->url->get('bpjs') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Kelola PPH21</span>
                            </a>
                        </li>
                    <?php elseif ($this->session->get('hak') == 'Manager Pabrik'): ?>

                        <li>
                            <a href="<?= $this->url->get('spl') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Pembuatan SPL</span>
                            </a>
                        </li>

                        <li class="text-muted menu-title">Navigation PPH21</li>
                        <li>
                            <a href="<?= $this->url->get('bpjs') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Laporan</span>
                            </a>
                        </li>
                    <?php elseif ($this->session->get('hak') == 'HRD'): ?>
                        <li>
                            <a href="<?= $this->url->get('index/pegawai') ?>" class="waves-effect"><i
                                        class="fa fa-user"></i> <span>Data Pengguna </span>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('pegawai') ?>" class="waves-effect"><i
                                        class="zmdi zmdi-folder-person"></i> <span> Data Pegawai </span>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('absen') ?>" class="waves-effect"><i
                                        class="fa fa-user"></i> <span>Data Master Absen</span>
                            </a>
                        </li>
                        <li class="text-muted menu-title">Navigation PPH21</li>
                        <li>
                            <a href="<?= $this->url->get('bpjs') ?>" class="waves-effect"><i
                                        class="fa fa-paperclip"></i> <span>Kelola PPH21</span>
                            </a>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?= $this->url->get('absen/detail/' . $this->session->get('nip')) ?>"
                               class="waves-effect"><i
                                        class="fa fa-clock-o"></i> <span>Laporan Penggajian</span>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('spl/detail/' . $this->session->get('nip')) ?>"
                               class="waves-effect"><i
                                        class="fa fa-clock-o"></i> <span>Surat Perintah Lembur</span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
                <div class="clearfix"></div>
            </div>
            <!-- Sidebar -->
            <div class="clearfix"></div>

        </div>

    </div>
    <!-- Left Sidebar End -->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <?= $this->getContent() ?>
            </div> <!-- container -->

        </div> <!-- content -->

        <footer class="footer">
            2016 © Gita Adryana.
        </footer>

    </div>


    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    <!-- Right Sidebar -->
    <div class="side-bar right-bar">
        <a href="javascript:void(0);" class="right-bar-toggle">
            <i class="zmdi zmdi-close-circle-o"></i>
        </a>
        <h4 class="">Notifications</h4>
        <div class="notification-list nicescroll">
            <ul class="list-group list-no-border user-list">
                <li class="list-group-item">
                    <a href="#" class="user-list-item">
                        <div class="avatar">
                            <img src="<?= $this->url->get('') ?>assets/images/users/avatar-2.jpg" alt="">
                        </div>
                        <div class="user-desc">
                            <span class="name">Michael Zenaty</span>
                            <span class="desc">There are new settings available</span>
                            <span class="time">2 hours ago</span>
                        </div>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="user-list-item">
                        <div class="icon bg-info">
                            <i class="zmdi zmdi-account"></i>
                        </div>
                        <div class="user-desc">
                            <span class="name">New Signup</span>
                            <span class="desc">There are new settings available</span>
                            <span class="time">5 hours ago</span>
                        </div>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="user-list-item">
                        <div class="icon bg-pink">
                            <i class="zmdi zmdi-comment"></i>
                        </div>
                        <div class="user-desc">
                            <span class="name">New Message received</span>
                            <span class="desc">There are new settings available</span>
                            <span class="time">1 day ago</span>
                        </div>
                    </a>
                </li>
                <li class="list-group-item active">
                    <a href="#" class="user-list-item">
                        <div class="avatar">
                            <img src="<?= $this->url->get('') ?>assets/images/users/avatar-3.jpg" alt="">
                        </div>
                        <div class="user-desc">
                            <span class="name">James Anderson</span>
                            <span class="desc">There are new settings available</span>
                            <span class="time">2 days ago</span>
                        </div>
                    </a>
                </li>
                <li class="list-group-item active">
                    <a href="#" class="user-list-item">
                        <div class="icon bg-warning">
                            <i class="zmdi zmdi-settings"></i>
                        </div>
                        <div class="user-desc">
                            <span class="name">Settings</span>
                            <span class="desc">There are new settings available</span>
                            <span class="time">1 day ago</span>
                        </div>
                    </a>
                </li>

            </ul>
        </div>
    </div>
    <!-- /Right-bar -->

</div>
<!-- END wrapper -->

<?php else: ?>
    <?= $this->getContent() ?>
<?php endif; ?>
<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="<?= $this->url->get('') ?>assets/js/jquery.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/bootstrap.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/detect.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/fastclick.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.slimscroll.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.blockUI.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/waves.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.nicescroll.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.scrollTo.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/switchery/switchery.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
<script type="text/javascript"
        src="<?= $this->url->get('') ?>assets/plugins/multiselect/js/jquery.multi-select.js"></script>
<script type="text/javascript"
        src="<?= $this->url->get('') ?>assets/plugins/jquery-quicksearch/jquery.quicksearch.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/select2/dist/js/select2.min.js" type="text/javascript"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"
        type="text/javascript"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-inputmask/bootstrap-inputmask.min.js"
        type="text/javascript"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/moment/moment.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"
        type="text/javascript"></script>
<!-- Datatables-->
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/jszip.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/pdfmake.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/vfs_fonts.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/buttons.print.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.fixedHeader.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/responsive.bootstrap.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/plugins/datatables/dataTables.scroller.min.js"></script>

<!-- Datatable init js -->
<script src="<?= $this->url->get('') ?>assets/pages/datatables.init.js"></script>

<!-- App js -->
<script src="<?= $this->url->get('') ?>assets/js/jquery.core.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.app.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable({keys: true});
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable({
            ajax: "<?= $this->url->get('') ?>assets/plugins/datatables/json/scroller-demo.json",
            deferRender: true,
            scrollY: 380,
            scrollCollapse: true,
            scroller: true
        });
        var table = $('#datatable-fixed-header').DataTable({fixedHeader: true});
    });
    TableManageButtons.init();

</script>

<script src="<?= $this->url->get('js/index.js') ?>"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $('#memberModal').modal('show');

    });
</script>
</body>
</html>